# Generated by Django 4.2.3 on 2023-08-04 12:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Аpplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('description', models.TextField()),
                ('date', models.DateField(blank=True, null=True)),
                ('date2', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Done', 'Done'), ('No processed', 'No processed')], default='No processed', max_length=32, null=True)),
                ('comments', models.TextField(blank=True, max_length='100', null=True)),
            ],
        ),
    ]
