# Generated by Django 4.2.3 on 2023-12-08 08:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='аpplication',
            old_name='date2',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='аpplication',
            name='comments',
            field=models.TextField(blank=True, max_length='100', null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='аpplication',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='аpplication',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='аpplication',
            name='status',
            field=models.CharField(blank=True, choices=[('Done', 'Done'), ('No processed', 'No processed')], default='No processed', max_length=32, null=True, verbose_name='Статус'),
        ),
    ]
