# Generated by Django 4.2.3 on 2023-12-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications_app', '0002_rename_date2_аpplication_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='аpplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='аpplication',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='аpplication',
            name='status',
            field=models.BooleanField(choices=[(0, 'Не обработано'), (1, 'Обработано')], default=0, max_length=32, verbose_name='Статус'),
        ),
    ]
